### ISSUE TITLE
API request for Iron Man 2 returns error

### ISSUE THREAD

**Issue by Bothari** [piplongrun/CSM.bundle#1]
Noticed Iron Man 2 didn't have a CSM rating, checked the API call and it comes back with an error.

`{"error":"No matches found.","code":"8003.2","search_string":"iron man 2","generated":"Fri, 07 Jul 2017 08:47:28 +0200"}`

API URL is here: https://api.tadata.me/csm/v2/?imdb_id=tt1228705

**Comment by Bothari** [comment]
Addendum:

Here's the CSM review page for the movie: https://www.commonsensemedia.org/movie-reviews/iron-man-2

**Comment by Bothari** [comment]
Here are some other movies that failed.

Aladdin: https://api.tadata.me/csm/v2/?imdb_id=tt0103639  https://www.commonsensemedia.org/movie-reviews/aladdin
Epic: https://api.tadata.me/csm/v2/?imdb_id=tt0848537  https://www.commonsensemedia.org/movie-reviews/epic
Up: https://api.tadata.me/csm/v2/?imdb_id=tt1049413 https://www.commonsensemedia.org/movie-reviews/up

After scanning my entire library it correctly updated about 600 of 650 movies, so pretty good completion rate! :)

It would also be awesome if there was a setting to add a default "CSM" rating to movies that the scanner was unable to identify. "CSM Unrated" or something similar.

**Comment by piplongrun** [comment]
Thanks for the report! I've made some changes and Iron Man 2, Aladdin and Epic are found this way. "Up" not being found has a different cause, because of the title being just 2 letters. I'm thinking about how this can be solved.

**Comment by piplongrun** [comment]
"Up" has also been fixed. Due to this title not showing up in any searches, I've added an option to maintain a list with "problematic matches" that I can fill with any movie that _is_ available, but cannot be found in search.

**Comment by piplongrun** [comment]
In v2.1 an option to set 'CSM Unrated' for movies that are not found has been added to the agent!
