### ISSUE TITLE
Set content rating age instead of content rating.

### ISSUE THREAD

**Issue by mastermatt** [piplongrun/CSM.bundle#4]
Currently the content rating in the metadata is being [set](https://github.com/piplongrun/CSM.bundle/blob/master/Contents/Code/__init__.py#L65) with a string constructed as
```python
metadata.content_rating = 'CSM %s' % (json_obj['recommended_age'])
```
However, the API docs allow the setting of `metadata.content_rating_age` which it describes as
> A string specifying the minumum age for viewers of the movie.

This seems like a much more appropriate place to set the recommended age from CSM.
Is would allow libraries to maintain the MPAA ratings and still have the CSM feedback for filtering.

**Comment by piplongrun** [comment]
That would be a nice idea, in theory, but this value is not used anywhere. It's not available when editing a movie and it's not part of the available filters.
