### ISSUE TITLE
Discussion:  Adding CSM-Rating as a Tag

### ISSUE THREAD

**Issue by p3hndrx** [piplongrun/CSM.bundle#7]
The plugin works like a dream.
However, I think we lose a lot of context by replacing the MPAA rating.

Is there any way to designate another field to populate the CSM rating into?
e.g. a Tag?

**Comment by piplongrun** [comment]
> Is there any way to designate another field to populate the CSM rating into?

Not that I know of. What you see in the web client as "tags" are some predefined fields, there isn't an option to create our own tags.
